[tool.briefcase]
project_name = "{{ cookiecutter.formal_name }}"
bundle = "{{ cookiecutter.bundle }}"
version = "{{ cookiecutter.version }}"
url = "{{ cookiecutter.project_url }}"
license = "{{ cookiecutter.license }}"
author = "{{ cookiecutter.author }}"
author_email = "{{ cookiecutter.author_email }}"

[tool.briefcase.app.bottle_spa]
formal_name = "{{ cookiecutter.formal_name }}"
description = "{{ cookiecutter.description }}"
icon = "src/resources/{{ cookiecutter.app_name }}"
sources = ['src']
requires = []


[tool.briefcase.app.bottle_spa.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.bottle_spa.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.bottle_spa.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.bottle_spa.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.bottle_spa.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
